### ISSUE TITLE
Remove babel and not use es6 module syntax

### ISSUE THREAD

**Issue by alfredosalzillo** [jfet97/arraymake#2]
It would be less confusing for the github community if this project is write all in ES3.

So it's better to remove _babel_ and the _es6 module syntax_ from the project.

**Comment by jfet97** [comment]
I do not agree. The package is backward compatible, but this does not mean I cannot use modern workflow tools. Import/Export syntax is used by Rollup to make the bundle. Babel is needed by Jest to perform tests.
